services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pix_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
